version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    target-branch: master
    registries:
      - maven-google
      - gradle-plugin
    groups:
      maven-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.android.library"
      - dependency-name: "com.android.application"
      - dependency-name: "dev.rikka.rikkax.widget:mainswitchbar"
      
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gradle-plugin:
    type: maven-repository
    url: "https://plugins.gradle.org/m2/"
