import xml.etree.ElementTree as ET
import itertools as it
import sys

# This script generates res/xml/method.xml.

def warn(msg):
    print("Warning: " + msg, file=sys.stderr)

def loc(loc_name, script, default_layout, **kwargs):
    return { "name": loc_name, "script": script,
             "default_layout": default_layout, **kwargs }

# The locales are defined here. To add support for a language, add it to the
# following block:

LOCALES = [
  loc("en_US", "latin", "latn_qwerty_us_old"),
  loc("en_US", "latin", "latn_qwerty_us"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_old"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_new"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru")
]

# The locale that is at the beginning of the list.
DEFAULT_LOCALE = "en_US"

def subtype_elem(root, loc):
    tag = loc["tag"].replace("_", "-")
    extra_keys = ",extra_keys=" + loc["extra_keys"] if "extra_keys" in loc else ""
    extra_value = f'script={loc["script"]},default_layout={loc["default_layout"]}{extra_keys}'
    ET.SubElement(root, "subtype", attrib={
        "android:label": "%s",
        "android:languageTag": tag,
        "android:imeSubtypeLocale": loc["name"],
        "android:imeSubtypeMode": "keyboard",
        "android:isAsciiCapable": "true",
        "android:imeSubtypeExtraValue": extra_value
        })

# Return locales in sorted order with the "tag" attribute added.
def compute_attrs():
    locales_grouped = {} # Locales grouped by language tag
    def lang(loc):
        return loc["name"].split("_")[0]
    for loc in LOCALES:
        locales_grouped.setdefault(lang(loc), []).append(loc)
    def tag(loc):
        l = lang(loc)
        if loc["name"] == l: return l # Locales like "en"
        if loc["name"] == f"{l}_{l.upper()}": return l # Locales like "fr_FR"
        # Return a short tag when it's not shared between several locales
        return l if len(locales_grouped[l]) == 1 else loc["name"]
    def add_attrs(loc):
        loc = dict(**loc)
        loc["tag"] = tag(loc)
        return loc
    return map(add_attrs, LOCALES)

def sort_locales(locales):
    # The default locale for a language (eg. "en") might shadow the exact
    # locale (eg. "en_US"). Makes sure the default locale sorts after the exact
    # ones.
    def key(l):
        s = l["name"].split("_")
        return (l["name"] != DEFAULT_LOCALE), s[0], (len(s) == 1), s[1:]
    return sorted(locales, key=key)

def gen():
    locales = sort_locales(compute_attrs())
    root = ET.Element("input-method", attrib={
        "xmlns:android": "http://schemas.android.com/apk/res/android",
        "android:settingsActivity": "juloo.keyboard2.SettingsActivity",
        "android:supportsSwitchingToNextInputMethod": "true",
        })
    root.append(ET.Comment(text=""" This file is automatically generated. DO NOT EDIT.
       Locales definitions should go into 'gen_method_xml.py'.
       Update this file with 'gradle test'.

  """))
    for loc in locales:
        subtype_elem(root, loc)
    ET.indent(root)
    print(ET.tostring(root, encoding="utf-8", xml_declaration=True).decode("UTF-8"))

gen()
