import xml.etree.ElementTree as ET
import itertools as it

# This script generates res/xml/method.xml.

def loc(loc_name, script, default_layout, **kwargs):
    return { "name": loc_name, "script": script,
            "default_layout": default_layout, **kwargs }

# The locales are defined here. To add support for a language, add it to the
# following block:

LOCALES = [
  loc("en_US", "latin", "latn_qwerty_us_old"),
  loc("en_US", "latin", "latn_qwerty_us"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_old"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_new"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru")
]

# The locale that is at the beginning of the list
DEFAULT_LOCALE = loc("en", "latin", "latn_qwerty_us_old", "latn_qwerty_us", tag="en")

def subtype_elem(root, loc):
    tag = loc["tag"].replace("_", "-")
    extra_keys = ",extra_keys=" + loc["extra_keys"] if "extra_keys" in loc else ""
    extra_value = f'script={loc["script"]},default_layout={loc["default_layout"]}{extra_keys}'
    ET.SubElement(root, "subtype", attrib={
        "android:label": "%s",
        "android:languageTag": tag,
        "android:imeSubtypeLocale": loc["name"],
        "android:imeSubtypeMode": "keyboard",
        "android:isAsciiCapable": "true",
        "android:imeSubtypeExtraValue": extra_value
        })

# Return locales in sorted order with the "tag" attribute
# added.
def compute_attrs():
    locales_grouped = {} # Locales grouped by language tag
    def lang(loc):
        return loc["name"].split("_")[0]
    for loc in LOCALES:
        locales_grouped.setdefault(lang(loc), []).append(loc)
    def tag(loc):
        if "tag" in loc: return loc["tag"]
        l = lang(loc)
        if loc["name"] == f"{l}_{l.upper()}": return l # Locales like "fr_FR"
        # Return a short tag when it's not shared between several locales
        return l if len(locales_grouped[l]) == 1 else loc["name"]
    def add_attrs(loc):
        return dict(tag=tag(loc), **loc)
    return map(add_attrs, LOCALES)

def gen():
    locales = compute_attrs()
    root = ET.Element("input-method", attrib={
        "xmlns:android": "http://schemas.android.com/apk/res/android",
        "android:settingsActivity": "juloo.keyboard2.SettingsActivity",
        "android:supportsSwitchingToNextInputMethod": "true",
        })
    root.append(ET.Comment(text=""" This file is automatically generated. DO NOT EDIT.
       Locales definitions should go into 'gen_method_xml.py'.
       Update this file with 'gradle test'.

  """))
    subtype_elem(root, DEFAULT_LOCALE)
    for loc in sorted(locales, key=lambda loc: loc["name"]):
        subtype_elem(root, loc)
    ET.indent(root)
    print(ET.tostring(root, encoding="utf-8", xml_declaration=True).decode("UTF-8"))

gen()
