import itertools as it

# This script generates res/xml/method.xml.

def loc(loc_name, script, default_layout, **kwargs):
    return { "name": loc_name, "script": script,
            "default_layout": default_layout, **kwargs }

# The locales are defined here. To add support for a language, add it to the
# following block:

LOCALES = [
  loc("en_US", "latin", "latn_qwerty_us_old"),
  loc("en_US", "latin", "latn_qwerty_us"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_old"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru_new"),
  loc("ru_RU", "latin", "cyrl_jcuken_ru")
]

# The locale that is at the beginning of the list
DEFAULT_LOCALE = loc("en", "latin", "latn_qwerty_us_old", "latn_qwerty_us", tag="en")

def loc_to_subtype(loc):
    tag = loc["tag"].replace("_", "-")
    extra_keys = ",extra_keys=" + loc["extra_keys"] if "extra_keys" in loc else ""
    return f'<subtype android:label="%s" android:languageTag="{tag}" android:imeSubtypeLocale="{loc["name"]}" android:imeSubtypeMode="keyboard" android:isAsciiCapable="true" android:imeSubtypeExtraValue="script={loc["script"]},default_layout={loc["default_layout"]}{extra_keys}"/>'

# Return locales in sorted order with the 'tag' item added.
def compute_tags():
    def lang(loc):
        return loc["name"].split("_")[0]
    locales_grouped = { k: list(v) for k, v in it.groupby(sorted(LOCALES, key=lang), lang) }
    def tag(loc):
        if "tag" in loc: return loc["tag"]
        l = lang(loc)
        if loc["name"] == f"{l}_{l.upper()}": return l # Locales like "fr_FR"
        # Return a short tag when it's not shared between several locales
        return l if len(locales_grouped[l]) == 1 else loc["name"]
    return [ dict(tag=tag(loc), **loc) for loc in LOCALES ]

def gen():
    locales = compute_tags()
    print(f"""<?xml version="1.0" encoding="utf-8"?>
<input-method xmlns:android="http://schemas.android.com/apk/res/android" android:settingsActivity="juloo.keyboard2.SettingsActivity" android:supportsSwitchingToNextInputMethod="true">
  <!-- This file is automatically generated. DO NOT EDIT.
       Locales definitions should go into 'gen_method_xml.py'.
       Update this file with 'gradle test'.

  -->
  {loc_to_subtype(DEFAULT_LOCALE)}
  {"\n  ".join(sorted(map(loc_to_subtype, locales)))}
</input-method>""")

gen()
