name: Check layouts

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  gen-layouts:
    name: Generated files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - run: python3 gen_layouts.py
    - name: "Check that the generated 'layouts.xml' is uptodate, otherwise run 'python3 gen_layouts.py'"
      run: git diff --exit-code
  check-layouts:
    name: check_layout.output
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - run: python3 check_layout.py
    - name: "Check that the generated 'check_layout.output' is uptodate, otherwise run 'python3 check_layout.py'"
      run: git diff --exit-code
