name: Check translations

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - run: python3 sync_translations.py
    - name: "Check that strings files are uptodate, otherwise run 'python3 sync_translations.py'"
      run: git add -N . && git diff --exit-code
